[project]
name = "bootoci"
version = "0.1.1"
requires-python = ">= 3.8"
description = "Convert OCI images to bootable ISO9660s using Docker and GRUB"
readme = "README.md"
license = "MIT"
maintainers = [{name = "Nadav Tasher", email = "hey@nadav.app"}]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
dependencies = [
	"jinja2",
]
keywords = ["docker", "oci", "iso9660"]

[project.urls]
Homepage = "https://github.com/NadavTasher/BootOCI"

[project.scripts]
bootoci = "bootoci.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
"*" = ["Dockerfile"]

[tool.distutils.bdist_wheel]
universal = false

[tool.yapf]
based_on_style = "google"
column_limit = 400
indent_width = 4